### ISSUE TITLE
What about creating "Outlets"

### ISSUE THREAD

**Issue by greensouth** [StefanNienhuis/homebridge-triggi#1]
For example, one url for "ON" and another one for "OFF" so we can manage outlets like the ones from KAKU or TRUST SMART HOME.

Would be really great.

**Comment by StefanNienhuis** [comment]
I would love to make that feature, unfortunately the Triggi Connect service doesn't support on/off urls, if they do, please let me know

**Comment by StefanNienhuis** [comment]
Because the Triggi Connect service doesn't support a URL with /on or /off, this is not possible with one connector, What would be possible, is two connectors and one accessory. Please let me know what you want.

EDIT:
Sorry my bad, i just discovered that you can use a value with 'connect.triggi.com/TOKEN?value=VALUE'. So you could have two triggs, one checks if the value is 1 then it turns for example a HUE light on, the other checks for 0 and then it turns off the hue light.

I will start working on this function today. Thanks for your feedback!

**Comment by StefanNienhuis** [comment]
Feature adder, i will now close this issue.

**Comment by StefanNienhuis** [comment]
Feature added, will close #1 now

**Comment by daaf84** [comment]
first had Triggi add-on, all worked. Bur nog I changed to Ostilo. Cant get it to work anymore with my trigs... first installed via webconfig (NPM), but had error. So installed from  the command line. No errors, but when I add the settings to the config.json, it crashes
